name: Build and Deploy Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 取得程式庫
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 建置 Writerside 文件
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          # 如果 writerside.cfg 位於專案根目錄，可改為 '.'；若在子資料夾 Writerside/，就用 'Writerside'
          location: Writerside

          # 多數 Writerside 專案會在 writerside.cfg 的 <instance> 內使用 module="Writerside" product="adoc"
          # 因此必須是 Writerside/adoc 而不是單純 adoc
          instance: 'Writerside/adoc'

          # 指定官方可用的 Docker Tag，例如 243.22562, latest, 等
          docker-version: '243.22562'

          # 輸出檔案名稱（可自訂）
          artifact: 'webHelpADOC2-all.zip'

        env:
          # 啟用詳細輸出
          LOG_LEVEL: DEBUG

      # 3. 上傳產出的 ZIP (以及其他需要的檔案) 為 Artifact，以便後續使用
      - name: Upload Writerside artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            webHelpADOC2-all.zip
            # 若還要上傳其他檔案或資料夾，也可一併列出

  deploy:
    # 表示本 Job 必須等待 build Job 完成
    needs: build
    runs-on: ubuntu-latest
    # 如要發布到 GitHub Pages，需要設定 Permissions
    permissions:
      id-token: write
      pages: write

    steps:
      # 1. 下載上一個 Job 上傳的 Artifact
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      # 2. 檢查剛下載的檔案
      - name: List artifacts directory
        run: ls -la artifacts/

      # 3. 解壓縮 Writerside 輸出 (webHelpADOC2-all.zip) 到 site/
      - name: Unzip website
        run: unzip artifacts/webHelpADOC2-all.zip -d site

      # 4. 啟用 GitHub Pages
      - name: Enable GitHub Pages
        uses: actions/configure-pages@v4

      # 5. 上傳「靜態網站」到 GitHub Pages Artifact
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # 6. 正式部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
